#! /usr/bin/env gosh
;;; -*- mode: scheme; coding: utf-8 -*-

(define random-init 3)

(define (rand-update x)
  (let ((a 16385)
	(b 997)
	(m 16777216))
    (remainder (+ (* a x) b) m)))

(define rand
  (let ((x random-init))
    (lambda ()
      (set! x (rand-update x))
      x)))

(define (main args)
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  (print (rand))
  0)
